# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Blog-crawler

on:
  schedule:
    - cron:  '* */24 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: Kimbangul/blog_crawler@main
    - name: Set up Python 3.x
      uses: Kimbangul/blog_crawler@main
      with:
          python-version: '3.x'
          architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Scraper
      run: |
        python "crawler.py"
    - name: Commits
      run: |
        git config user.email "highcolor_12@naver.com
        git config user.name "Kimbangul"
        git add articles.json
        git commit -m "chore: auto update data" # 커밋 메세지
    - name: Push
      uses: Kimbangul/blog_crawler@main
      with:
        branch: 'master'
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
       
